package com.robotopia.androidstudiolite.designsystem.color

import androidx.compose.ui.graphics.Color

/** Semantic color tokens for IDE chrome (islands, menus, editor, accents). */
data class ColorScheme(
    val Bg: Color,
    val Canvas: Color,
    val CanvasTop: Color,
    val CanvasBottom: Color,
    val Surface: Color,
    val Surface2: Color,
    val Input: Color,
    val Menu: Color,
    val MenuBorder: Color,
    val MenuDivider: Color,
    val Editor: Color,
    val Border: Color,
    val Text: Color,
    val Muted: Color,
    val Muted2: Color,
    val Gutter: Color,
    val Primary: Color,
    val OnPrimary: Color,
    val Run: Color,
    val Danger: Color,
    val Warning: Color,
    val Selection: Color,
    val CodeString: Color,
    val CodeAnnotation: Color,
    val CodeKeyword: Color,
    val CodeFunction: Color,
    val CodeComment: Color,
    val CodeNumber: Color,
    val Disabled: Color,
)

/** JetBrains New UI / Islands Dark — product default. */
val DarkColorScheme = ColorScheme(
    Bg = Color(0xFF1E1F22),
    Canvas = Color(0xFF2B2D30),
    CanvasTop = Color(0xFF34363D),
    CanvasBottom = Color(0xFF2B2D30),
    Surface = Color(0xFF2B2D30),
    Surface2 = Color(0xFF26282B),
    Input = Color(0xFF26282B),
    Menu = Color(0xFF2B2D30),
    MenuBorder = Color(0xFF4E5157),
    MenuDivider = Color(0xFF393B40),
    Editor = Color(0xFF1E1F22),
    Border = Color(0xFF43454A),
    Text = Color(0xFFDFE1E5),
    Muted = Color(0xFF6F737A),
    Muted2 = Color(0xFF5A5D63),
    Gutter = Color(0xFF5A5D63),
    Primary = Color(0xFF3574F0),
    OnPrimary = Color(0xFFFFFFFF),
    Run = Color(0xFF499C54),
    Danger = Color(0xFFD17474),
    Warning = Color(0xFFF2C55C),
    Selection = Color(0xFF2E436E),
    CodeString = Color(0xFF6AAB73),
    CodeAnnotation = Color(0xFF57AAF7),
    CodeKeyword = Color(0xFFCF8E6D),
    CodeFunction = Color(0xFF56A8F5),
    CodeComment = Color(0xFF7A7E85),
    CodeNumber = Color(0xFF2AACB8),
    Disabled = Color(0xFF4E5157),
)

/**
 * Test Islands Light palette — for design-system previews.
 * Not wired as an app runtime theme yet.
 */
val LightColorScheme = ColorScheme(
    Bg = Color(0xFFFFFFFF),
    Canvas = Color(0xFFEBECF0),
    CanvasTop = Color(0xFFF7F8FA),
    CanvasBottom = Color(0xFFEBECF0),
    Surface = Color(0xFFFFFFFF),
    Surface2 = Color(0xFFF2F3F5),
    Input = Color(0xFFF2F3F5),
    Menu = Color(0xFFFFFFFF),
    MenuBorder = Color(0xFFC9CCD6),
    MenuDivider = Color(0xFFD3D5DB),
    Editor = Color(0xFFFFFFFF),
    Border = Color(0xFFC9CCD6),
    Text = Color(0xFF27282E),
    Muted = Color(0xFF6C707E),
    Muted2 = Color(0xFF818594),
    Gutter = Color(0xFF818594),
    Primary = Color(0xFF3574F0),
    OnPrimary = Color(0xFFFFFFFF),
    Run = Color(0xFF369650),
    Danger = Color(0xFFDB5C5C),
    Warning = Color(0xFFC29B37),
    Selection = Color(0xFFD4E5FF),
    CodeString = Color(0xFF067D17),
    CodeAnnotation = Color(0xFF00627A),
    CodeKeyword = Color(0xFF0033B3),
    CodeFunction = Color(0xFF00627A),
    CodeComment = Color(0xFF8C8C8C),
    CodeNumber = Color(0xFF1750EB),
    Disabled = Color(0xFFC9CCD6),
)

/**
 * [Dracula](https://draculatheme.com) — popular editor palette, for DS previews.
 * Not wired as an app runtime theme yet.
 */
val DraculaColorScheme = ColorScheme(
    Bg = Color(0xFF282A36),
    Canvas = Color(0xFF21222C),
    CanvasTop = Color(0xFF343746),
    CanvasBottom = Color(0xFF21222C),
    Surface = Color(0xFF44475A),
    Surface2 = Color(0xFF343746),
    Input = Color(0xFF343746),
    Menu = Color(0xFF343746),
    MenuBorder = Color(0xFF6272A4),
    MenuDivider = Color(0xFF44475A),
    Editor = Color(0xFF282A36),
    Border = Color(0xFF6272A4),
    Text = Color(0xFFF8F8F2),
    Muted = Color(0xFF6272A4),
    Muted2 = Color(0xFF6D79A8),
    Gutter = Color(0xFF6272A4),
    Primary = Color(0xFFBD93F9),
    OnPrimary = Color(0xFF282A36),
    Run = Color(0xFF50FA7B),
    Danger = Color(0xFFFF5555),
    Warning = Color(0xFFF1FA8C),
    Selection = Color(0xFF44475A),
    CodeString = Color(0xFFF1FA8C),
    CodeAnnotation = Color(0xFF8BE9FD),
    CodeKeyword = Color(0xFFFF79C6),
    CodeFunction = Color(0xFF50FA7B),
    CodeComment = Color(0xFF6272A4),
    CodeNumber = Color(0xFFBD93F9),
    Disabled = Color(0xFF6272A4),
)
